on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: set-up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install depenencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite

      - name: Run pytest
        run: pytest tests

      - name: Run mypy
        run: |
          cd ..

          mv homework-with-actions homework_with_actions
          cd homework_with_actions
          python -m mypy .
    
      - name: Run black check
        run: black --diff --check .
    
      - name: Run isort check
        run: isort --check-only .  
        
      - name: Run flake8
        run: flake8 . 
